site_name: Example Documentation
theme:
  name: material
extra:
  analytics:
    provider: google
    property: G-B7ZFRMHGEK
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list